name: network_guardian
description: "A Flutter package that monitors internet connectivity and shows customizable toast notifications when connection is lost."
version: 0.0.1
homepage: https://github.com/pratik-singh-idealake/network_guardian
repository: https://github.com/pratik-singh-idealake/network_guardian

environment:
  sdk: ^3.9.2
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
